# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Wyklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Wykladowca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='wyklad',
            name='wykladowca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapisy.Wykladowca'),
        ),
    ]
