# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyklad',
            name='studenci',
            field=models.ManyToManyField(to='zapisy.Student'),
        ),
    ]
