# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0003_student_nazwisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='wykladowca',
            name='nazwisko',
            field=models.CharField(default='nazwisko', max_length=40),
            preserve_default=False,
        ),
    ]
